version: "3.9"

services:
  api: 
    image: crosspay/cross-pay-api:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=payments-db
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 1
    networks:
      - project-network
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 1
    networks:
      - project-network
  
networks:
  project-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.18.0.1/24